name: Snyk SAST Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  snyk-sast:
    name: Run Snyk SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk Code Test
        run: snyk code test

      - name: Upload Snyk Code Test Results
        uses: actions/upload-artifact@v2
        with:
          name: snyk-sast-report
          path: snyk-report.json

      - name: Convert Snyk Report to HTML
        run: snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Upload Snyk Report HTML
        uses: actions/upload-artifact@v2
        with:
          name: snyk-sast-report-html
          path: snyk-report.html
